"""
optimized_phases.py
Crest-factor-optimised initial phases for an equally spaced N-tone static array.

Generated by optimize_phases.py.  Objective: the maximum of the analytic envelope
|sum_k w_k exp(i(2 pi f_k t + phi_k))| over one beat period, i.e. exactly the
`peak_of_sum()` used by sorter.py / hold_array.py, in units of one tone at w=1.

VALIDITY.  For an equally spaced set f_k = f0 + k*df, factoring out exp(i 2 pi f0 t)
and substituting tau = df*t removes both f0 and df from the objective.  So these
phases are correct for ANY start frequency and ANY site spacing, and in particular
snapping the array onto the DDS grid does not invalidate them.

They ARE tied to the amplitude RATIOS (equal weights here).  If you hand-tune
AMPLITUDES_CH0, re-run optimize_phases.py with those weights.

Columns below: peak = envelope peak; CF = crest factor peak/sqrt(sum w^2 / 2);
floor = sqrt(n), the CF=sqrt(2) theoretical limit; a_k = 0.95/peak, the per-tone
amplitude at STATIC_HEADROOM=0.95; last column is power vs Schroeder phases.
"""

import numpy as np

OPTIMIZED_STATIC_PHASES = {
    #2: np.array([
    #    0.000000000, 5.893002817,
    #]),  # peak 2.0000  CF 2.0000  a_k 0.4750  (1.00x Schroeder power)
    #3: np.array([
    #    0.000000000, 2.837072354, 2.532552054,
    #]),  # peak 2.2361  CF 1.8257  a_k 0.4249  (1.40x Schroeder power)
    #4: np.array([
    #    0.000000000, 4.245944305, 0.399539017, 1.027154751,
    #]),  # peak 2.4722  CF 1.7481  a_k 0.3843  (1.31x Schroeder power)
    #5: np.array([
    #    0.000000000, 4.836202337, 5.610834498, 6.121596831,
    #    2.570788983,
    #]),  # peak 2.7373  CF 1.7312  a_k 0.3471  (1.16x Schroeder power)
    #6: np.array([
    #    0.000000000, 3.495693520, 3.047569422, 5.211712299,
    #    3.704936842, 4.537529075,
    #]),  # peak 3.0461  CF 1.7587  a_k 0.3119  (1.30x Schroeder power)
    #7: np.array([
    #    0.000000000, 0.111997187, 0.223994321, 3.477584104,
    #    3.589581326, 0.559985658, 3.813575614,
    #]),  # peak 3.1034  CF 1.6588  a_k 0.3061  (1.40x Schroeder power)
    #8: np.array([
    #    0.000000000, 0.687483666, 0.009952559, 1.347133721,
    #    3.597969719, 0.479275254, 5.658478364, 3.189481405,
    #]),  # peak 3.2250  CF 1.6125  a_k 0.2946  (1.38x Schroeder power)
    #9: np.array([
    #    0.000000000, 3.265019684, 0.946922291, 3.665371464,
    #    4.703362178, 0.340513057, 0.580390778, 5.856815065,
    #    5.550122389,
    #]),  # peak 3.3406  CF 1.5748  a_k 0.2844  (1.58x Schroeder power)
    #10: np.array([
    #    0.000000000, 4.246384259, 6.045949022, 4.454788343,
    #    4.047238774, 2.052010862, 5.614987675, 0.105268090,
    #    1.380864360, 2.601517420,
    #]),  # peak 3.6403  CF 1.6280  a_k 0.2610  (1.39x Schroeder power)
    11: np.array([
        0.000000000, 0.880838963, 5.889411010, 0.047468498,
        6.187359970, 2.296769551, 4.125590738, 2.207115345,
        5.987288629, 5.200132657, 2.257524468,
    ]),  # peak 3.6837  CF 1.5707  a_k 0.2579  (1.50x Schroeder power)
}
